[theme]
theme = "solarized-dark"
[icons]
icons = "material-nf"

[[block]]
block = "custom"
command = "spt playback --format"
interval = 3
[[block.click]]
button = "left"
cmd = "spt playback --toggle"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon / $available "
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[[block.click]]
button = "right"
cmd = "/usr/bin/baobab"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
format = " $icon /home $available "
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[[block.click]]
button = "right"
cmd = "/usr/bin/baobab"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3) "
format_alt = " $icon $mem_used_percents.eng(w:1) "
interval = 10

[[block]]
block = "cpu"
interval = 3
format = " $icon $utilization "
format_alt = " $icon $barchart $frequency.eng(w:3) "

[[block]]
block = "net"
format = " $icon $ip "
format_alt = " $icon {$signal_strength $ssid $frequency|wire} via $device "
[[block.click]]
button = "right"
cmd = "/usr/bin/gnome-control-center wifi"

[[block]]
block = "pacman"
interval = 600
error_interval = 300
format = " $icon $pacman + $aur = $both updates available "
format_singular = " $icon $both update available "
format_up_to_date = " $icon system up to date "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"
[[block.click]]
button = "right"
cmd = "/usr/bin/pamac-manager"
[[block.click]]
button = "left"
update = true

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %v %R', l:en_US) "
short = " $icon $timestamp.datetime(f:%R) "

