
theme = "solarized-dark"
icons = "awesome"
#icons = "material-nf"


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
clickable = false

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "ens33"
format = "{ip}"
interval = 5


[[block]]
block = "net"
device = "ens38"
format = "{ip}"
interval = 5
hide_inactive = true

[[block]]
block = "apt"
interval = 1800
format = "{count:1} updates available"
format_singular = "{count:1} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# shows dmenu with cached available updates. Any dmenu alternative should also work.
on_click = "APT_CONFIG=/tmp/i3rs-apt/apt.conf apt list --upgradable | tail -n +2 | rofi -dmenu"


[[block]]
block = "sound"


[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

